config/routes.rb
Rails.application.routes.draw do
# エンドユーザー用
# URL /users/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
registrations: "public/registrations",
sessions: 'public/sessions'
}

devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
end

#エンドユーザー側ルーティング
scope module: :public do

  get 'matchings/seach' => 'matchings#seach'

  resources :matchings, only: [:index]
  resources :reactions, only: [:create]
  resources :chat_rooms, only: [:create, :show]
  resources :notifications, only: [:index]
  resources :activity_points, only: [:new, :create, :show, :edit, :update, :destroy]

  get 'users/info' => 'users#info'
  get 'users/matching' => 'users#matching'
  get 'users/unsubscribe' => 'users#unsubscribe'
  patch 'users/withdraw' => 'users#withdraw'
  resources "users", path: 'users/my_page', only: [:show, :edit, :update]

  root to: "homes#top"
  get "about" => "homes#about", as: "about"

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity_point.rb
class ActivityPoint < ApplicationRecord

  belongs_to :user

  enum activity_status: { photographer: 0, subject: 1 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord

  belongs_to :user

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord

  has_many :chat_room_users
  has_many :chat_messages
  has_many :users, through: :chat_room_users

end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord

  belongs_to :chat_room
  belongs_to :user

end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope -> { order(created_at: :desc) }
  belongs_to :reaction, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true

end

app/models/reaction.rb
class Reaction < ApplicationRecord

  has_many :notifications, dependent: :destroy
  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one_attached :profile_image
  has_many :activity_points
  has_many :reactions
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy


# ゲストログインメソッド
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

# プロフィール画像
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matchings_helper.rb
module MatchingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Photolink</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to users_matching_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> マッチング
            <% end %>
          </li>
          <li>
            <%=  link_to new_activity_point_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> 活動地点
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Top
            <% end %>
          </li>
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photolink</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
      <main>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>